In [5]:
import seaborn as sea    # 고급 데이터 시각화 라이브러리
import numpy as num       # 계산 연산 통계

In [12]:
print(sea.get_dataset_names())   # get_dataset_names 라이브러리의 데이터셋 목록 확인
print(num.__version__)           # 버전 확인
print(dir(num))                  # 함수 확인

['anagrams', 'anscombe', 'attention', 'brain_networks', 'car_crashes', 'diamonds', 'dots', 'dowjones', 'exercise', 'flights', 'fmri', 'geyser', 'glue', 'healthexp', 'iris', 'mpg', 'penguins', 'planets', 'seaice', 'taxis', 'tips', 'titanic']
1.23.5
['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', 

NameError: ignored

오픈 데이터셋
- 공공 데이터 포탈
- Data.gov
- 캐글
- FiveThirtyEight
- 데이터 월드
- 구글 데이터셋 검색
- UC 어바인 머신러닝 레포지토리
- 나스닥 퀸들
- 월드 뱅크 오픈 데이터

In [19]:
data_1 = [5, 9, 2.5, 3, 1]
array_1 = num.array(data_1)    # 순차형 객체를 넘파이 배열로.
print(array_1)

data_2 = [[1, 3, 5, 7, 9],[2, 4, 6, 8, 10]]   # 같은 길이의 리스트를 포함한 순차 데이터 -> 동일한 다차원 배열로
array_2 = num.array(data_2)
print(array_2)

print(array_2.ndim)    # 차원
print(array_2.shape)   # 차원의 크기
print(array_1.dtype)   # 데이터 타입. 다른 게 나옴.
print(array_2.dtype)

[5.  9.  2.5 3.  1. ]
[[ 1  3  5  7  9]
 [ 2  4  6  8 10]]
2
(2, 5)
float64
int64


In [22]:
num.zeros(10)   # 0으로 채워진 배열

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
num.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
num.ones((2,3,8))   # 1로 채워진 배열

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [25]:
num.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
num.arange(5, 30, 3)   # 시작, 종료, 단계 지정

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29])

In [27]:
array_1 = num.array([1,3,5,7,9], dtype=num.float32)   # type 지정
array_2 = num.array([1,3,5,7.9], dtype=num.int16)

print(array_1.dtype)
print(array_2.dtype)

In [32]:
array_2_float = array_2.astype(num.float64)   # astype으로 타입 바꿀 수 있음.
array_2_float.dtype

dtype('float64')